@startuml

class App
{
    +ArrayList<String> name

    +void writeToFile(ArrayList<String> name)
    +void sortArray(ArrayList<String> name)
    +ArrayList<String> parseName()
    +void main()

}

@enduml